'use strict';
const fs=require('fs'),path=require('path');
const ROOT=path.resolve(__dirname,'../..');
const SITE='https://www.kenturnerlaw.com';
const CONTENT=path.join(ROOT,'content','posts');
const MARK='kt-generated-v2';
const MANAGED_START='<!-- kt-managed-posts:start -->',MANAGED_END='<!-- kt-managed-posts:end -->';
const hubs={
 'criminal-defense':{dir:'florida-criminal-defense-answers',title:'Florida Criminal Defense Answers',intro:'Direct answers about Florida criminal cases, police encounters, arrests, DUI, searches, and court procedure.'},
 'family-law':{dir:'florida-family-law-answers',title:'Florida Family Law Answers',intro:'Direct answers about Florida divorce, parenting plans, time-sharing, child support, paternity, modification, and relocation.'},
 'traffic':{dir:'florida-traffic-ticket-answers',title:'Florida Traffic Ticket Answers',intro:'Direct answers about Florida traffic tickets, license consequences, court, and attorney representation.'},
 'general':{dir:'florida-legal-answers',title:'Florida Legal Answers',intro:'Plain-English answers to common Florida legal questions.'},
 'updates':{dir:'updates',title:'Legal Updates',intro:'Recent legal information and updates from Ken Turner.'}
};
function esc(s){return String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function attr(s){return esc(s).replace(/'/g,'&#39;')}
function readPosts(){if(!fs.existsSync(CONTENT))return[];return fs.readdirSync(CONTENT).filter(f=>f.endsWith('.json')).map(f=>{const p=JSON.parse(fs.readFileSync(path.join(CONTENT,f),'utf8'));if(!p.practiceArea)p.practiceArea=p.type==='update'?'updates':(p.category==='Family law'?'family-law':'criminal-defense');return p}).sort((a,b)=>String(b.dateModified||b.datePublished||'').localeCompare(String(a.dateModified||a.datePublished||'')))}
function hub(p){return hubs[p.practiceArea]||hubs['criminal-defense']}
function urlPath(p){const h=hub(p);return `/${h.dir}/${p.slug}/`}
function outFile(p){return path.join(ROOT,urlPath(p).replace(/^\//,''),'index.html')}
function dateTime(v){if(!v)return'';const d=new Date(v);return new Intl.DateTimeFormat('en-US',{month:'long',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit',timeZone:'America/New_York',timeZoneName:'short'}).format(d)}
function paragraphs(body){return String(body||'').replace(/\r\n/g,'\n').trim().split(/\n\s*\n/).map(x=>x.trim()).filter(Boolean)}
function inline(s){let text=esc(s);text=text.replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+|\/[^\s)]*)\)/g,(m,label,url)=>{const external=/^https?:\/\//.test(url)&&!url.startsWith(SITE);return `<a href="${attr(url)}"${external?' target="_blank" rel="noopener"':''}>${label}</a>`});text=text.replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/_([^_]+)_/g,'<em>$1</em>');return text}
function bodyHtml(body){return paragraphs(body).map(p=>{if(/^##\s+/.test(p))return `<h2>${inline(p.replace(/^##\s+/,''))}</h2>`;if(/^[-*]\s+/m.test(p)){const items=p.split('\n').map(x=>x.replace(/^[-*]\s+/, '').trim()).filter(Boolean);return `<ul>${items.map(x=>`<li>${inline(x)}</li>`).join('')}</ul>`}return `<p>${inline(p.replace(/\n/g,' '))}</p>`}).join('\n')}
const CSS=`*{box-sizing:border-box}body{margin:0;background:#fff;color:#171717;font-family:Georgia,"Times New Roman",serif;line-height:1.7}.top{background:#111;color:#fff;padding:12px 18px;font-family:Arial,sans-serif}.top a{color:#fff;text-decoration:none}.top .call{float:right}.page{max-width:820px;margin:auto;padding:28px 22px 60px}.crumbs{font:14px Arial,sans-serif;color:#555;margin-bottom:24px}.crumbs a{color:#333}.kicker{font:700 13px Arial,sans-serif;letter-spacing:.08em;text-transform:uppercase;color:#555;margin:0 0 10px}h1{font-size:clamp(2.1rem,6vw,4.1rem);line-height:1.04;letter-spacing:-.025em;margin:0 0 18px;color:#111}.byline{font:16px Arial,sans-serif;border-top:1px solid #222;border-bottom:1px solid #ccc;padding:12px 0;margin:0 0 30px}.byline strong{display:block}.article{font-size:1.18rem}.article p{margin:0 0 1.35em}.article h2{font-size:1.65rem;line-height:1.2;margin:1.8em 0 .6em}.article a{color:#0645ad;text-decoration:underline}.article li{margin:.45em 0}.related{border-top:3px solid #111;margin-top:42px;padding-top:18px}.related h2{font:700 1.1rem Arial,sans-serif;text-transform:uppercase;letter-spacing:.05em}.meta{font:14px Arial,sans-serif;color:#555;margin-top:30px}footer{font:14px Arial,sans-serif;border-top:1px solid #ccc;padding-top:18px;margin-top:42px}@media(max-width:600px){.page{padding:22px 16px 44px}.article{font-size:1.08rem}.top .call{float:none;display:block;margin-top:5px}}`;
function page(p){const h=hub(p),u=SITE+urlPath(p),desc=(paragraphs(p.body)[0]||p.title).replace(/\s+/g,' ').slice(0,155);const published=dateTime(p.datePublished),modified=dateTime(p.dateModified);const isUpdated=p.dateModified&&p.datePublished&&p.dateModified!==p.datePublished;const about=[p.category,p.county?`${p.county} County`:null].filter(Boolean);const schema={'@context':'https://schema.org','@type':p.practiceArea==='updates'?'BlogPosting':'Article',headline:p.title,datePublished:p.datePublished,dateModified:p.dateModified||p.datePublished,description:desc,author:{'@type':'Person',name:'Ken Turner',jobTitle:'Florida Attorney',url:SITE+'/'},publisher:{'@type':'LegalService',name:'Ken Turner Law',url:SITE+'/'},mainEntityOfPage:u,about};return `<!doctype html>\n<!-- ${MARK}: source content/posts/${esc(p.slug)}.json -->\n<html amp lang="en"><head><meta charset="utf-8"><script async src="https://cdn.ampproject.org/v0.js"></script><link rel="canonical" href="${attr(u)}"><meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1"><meta name="robots" content="index,follow"><title>${esc(p.title)} | Ken Turner Law</title><meta name="description" content="${attr(desc)}"><meta property="og:type" content="article"><meta property="og:title" content="${attr(p.title)}"><meta property="og:description" content="${attr(desc)}"><meta property="og:url" content="${attr(u)}"><script type="application/ld+json">${JSON.stringify(schema)}</script><style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;animation:none}</style></noscript><style amp-custom>${CSS}</style></head><body><header class="top"><a href="/">Ken Turner Law</a><a class="call" href="tel:2394003733">Call (239) 400-3733</a></header><main class="page"><nav class="crumbs"><a href="/">Home</a> › <a href="/${h.dir}/">${esc(h.title)}</a> › ${esc(p.title)}</nav><p class="kicker">${esc(p.category||h.title)}${p.county?' • '+esc(p.county)+' County':''}</p><h1>${esc(p.title)}</h1><div class="byline"><strong>By Ken Turner</strong><span>Published ${esc(published)}</span>${isUpdated?`<br><span>Updated ${esc(modified)}</span>`:''}</div><article class="article">${bodyHtml(p.body)}</article><div class="meta">Florida legal information${p.county?' • '+esc(p.county)+' County':''}</div><section class="related"><h2>More from Ken Turner Law</h2><p><a href="/${h.dir}/">${esc(h.title)}</a> • <a href="/practice-areas/">Practice Areas</a> • <a href="https://kenturnerlaw.as.me/">Schedule a Phone Appointment</a></p></section><footer><p>This page provides general information and is not legal advice.</p><p>Ken Turner Law • Naples, Florida • (239) 400-3733</p></footer></main></body></html>`}
function write(file,data){fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,data,'utf8')}
function removeOrphans(posts){const keep=new Set(posts.map(p=>path.resolve(outFile(p))));Object.values(hubs).forEach(h=>{const root=path.join(ROOT,h.dir);if(!fs.existsSync(root))return;for(const ent of fs.readdirSync(root,{withFileTypes:true})){if(!ent.isDirectory())continue;const f=path.join(root,ent.name,'index.html');if(!fs.existsSync(f))continue;const html=fs.readFileSync(f,'utf8');if(html.includes(MARK)&&!keep.has(path.resolve(f)))fs.rmSync(path.dirname(f),{recursive:true,force:true})}})}
function plainTitle(s){return String(s||'').replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&nbsp;/g,' ').replace(/\s+/g,' ').replace(/\s+\|\s+Ken Turner Law.*$/i,'').trim()}
function manualHubEntries(h,posts){const generated=new Set(posts.map(p=>path.resolve(outFile(p))));const root=path.join(ROOT,h.dir);if(!fs.existsSync(root))return[];return fs.readdirSync(root,{withFileTypes:true}).filter(e=>e.isDirectory()).map(e=>{const f=path.join(root,e.name,'index.html');if(!fs.existsSync(f)||generated.has(path.resolve(f)))return null;const html=fs.readFileSync(f,'utf8');if(html.includes(MARK))return null;const hm=html.match(/<h1\b[^>]*>([\s\S]*?)<\/h1>/i);const tm=html.match(/<title\b[^>]*>([\s\S]*?)<\/title>/i);const title=plainTitle((hm&&hm[1])||(tm&&tm[1])||e.name);return title?{title,url:`/${h.dir}/${e.name}/`}:null}).filter(Boolean).sort((a,b)=>a.title.localeCompare(b.title))}
function hubIndex(h,posts){const generated=posts.map(p=>`<article><h2><a href="${attr(urlPath(p))}">${esc(p.title)}</a></h2><p>${esc(dateTime(p.datePublished))}${p.county?' • '+esc(p.county)+' County':''}${p.category?' • '+esc(p.category):''}</p></article>`).join('\n');const manual=manualHubEntries(h,posts).map(x=>`<article><h2><a href="${attr(x.url)}">${esc(x.title)}</a></h2><p>Ken Turner Law legal answer</p></article>`).join('\n');const list=[generated,manual].filter(Boolean).join('\n')||'<p>No articles published yet.</p>';return `<!doctype html><html amp lang="en"><head><meta charset="utf-8"><script async src="https://cdn.ampproject.org/v0.js"></script><link rel="canonical" href="${SITE}/${h.dir}/"><meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1"><title>${esc(h.title)} | Ken Turner Law</title><meta name="description" content="${attr(h.intro)}"><style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;animation:none}</style></noscript><style amp-custom>${CSS}article{border-top:1px solid #ccc;padding:18px 0}article h2{margin:0 0 5px;font-size:1.5rem}article p{font:14px Arial,sans-serif;color:#555}</style></head><body><header class="top"><a href="/">Ken Turner Law</a><a class="call" href="tel:2394003733">Call (239) 400-3733</a></header><main class="page"><p class="kicker">Answer Center</p><h1>${esc(h.title)}</h1><p class="article">${esc(h.intro)}</p>${list}</main></body></html>`}
function collectUrls(){const skip=new Set(['node_modules','.git','.github','content','tools','functions','publish','test','handbook','img','images','assets','search']);const urls=new Set([SITE+'/']);function walk(dir,base=''){for(const e of fs.readdirSync(dir,{withFileTypes:true})){if(e.name.startsWith('.'))continue;if(!base&&skip.has(e.name))continue;const rel=path.join(base,e.name),full=path.join(dir,e.name);if(e.isDirectory())walk(full,rel);else if(e.name==='index.html')urls.add(SITE+(base?'/'+base.replace(/\\/g,'/')+'/':'/'))}}walk(ROOT);return [...urls].sort()}
function build(){const posts=readPosts();removeOrphans(posts);posts.forEach(p=>write(outFile(p),page(p)));Object.entries(hubs).forEach(([key,h])=>write(path.join(ROOT,h.dir,'index.html'),hubIndex(h,posts.filter(p=>p.practiceArea===key))));const urls=collectUrls();write(path.join(ROOT,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+urls.map(u=>`  <url><loc>${u}</loc></url>`).join('\n')+'\n</urlset>\n');const search=posts.map(p=>({title:p.title,url:urlPath(p),type:p.type,practiceArea:p.practiceArea,category:p.category||'',county:p.county||'',description:paragraphs(p.body)[0]||'',datePublished:p.datePublished,dateModified:p.dateModified||p.datePublished}));write(path.join(ROOT,'search','published.json'),JSON.stringify(search,null,2)+'\n');console.log(`Built ${posts.length} published articles across ${Object.keys(hubs).length} sections.`)}
build();
